project_id = "gramola"

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = false

[storage]
enabled = false

[auth]
enabled = false

[realtime]
enabled = true

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000
